# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source :gemcutter


gem "hoe-bundler", "~>1.1", :group => [:development, :test]
gem "rdoc", "~>3.10", :group => [:development, :test]
gem "hoe", "~>2.13", :group => [:development, :test]

# vim: syntax=ruby
