# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source :gemcutter

gem "rdoc", "~>3.10"

group :development, :test do
  gem "hoe", "~>2.13"
  gem "hoe-bundler", "~>1.1"
  gem "hoe-gemspec2", "~>1.0"
end

# vim: syntax=ruby
